spring:
  datasource:
    url: jdbc:h2:mem:pokedex;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  data:
    redis:
      host: localhost
      port: 6379
    cache:
      type: redis
server:
  port: 8080
  error:
    include-message: always
    include-exception: true

logging:
  level:
    dev.pokedex.weather: INFO           # tes logs (WeatherCacheService / WeatherClient)
    org.springframework.cache: TRACE    # montre hit/miss/put au cache
    org.springframework.data.redis: DEBUG  # connexion Redis & ops